let root = process.env.PUBLIC_URL
const skillsList = [
    {
        id:1,
        title:"HTML5",
        image:`${root}/logo/html5.svg`,
        url:"https://www.w3.org/html"
    },
    {
        id:2,
        title:"CSS3",
        image:`${root}/logo/css3.svg`,
        url:"https://www.w3.org/Style/CSS/Overview.en.html"
    },
    {
        id:3,
        title:"JavaScript",
        image:`${root}/logo/js.svg`,
        url:"https://developer.mozilla.org/en-US/docs/Web/JavaScript"
    },
    {
        id:4,
        title:"React",
        image:`${root}/logo/react.svg`,
        url:"https://reactjs.org/"
    },
    {
        id:5,
        title:"Redux",
        image:`${root}/logo/redux.svg`,
        url:"https://redux.js.org/"
    },
    {
        id:6,
        title:"Express",
        image:`${root}/logo/express.svg`,
        url:"https://expressjs.com/"
    },
    {
        id:7,
        title:"NodeJS",
        image:`${root}/logo/nodejs.svg`,
        url:"https://nodejs.org/"
    },
    {
        id:8,
        title:"MongoDB",
        image:`${root}/logo/mongodb.svg`,
        url:"https://www.mongodb.com/"
    },
    {
        id:9,
        title:"GitHub",
        image:`${root}/logo/github.svg`,
        url:"https://github.com/"
    }
    ,
    {
        id:10,
        title:"DS & Algorithm",
        image:`${root}/logo/dsa.png`,
        url:"#"
    }
]

export default skillsList